// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bblrxervgwkphkctdghe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJibHJ4ZXJ2Z3drcGhrY3RkZ2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjQ1NjYsImV4cCI6MjA3NDEwMDU2Nn0.BBzc0XFxI5c7BkfRQrNLW-pBCeS60NjvXPpRcXmlfR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});